-- Q10. Revenue Analysis

-- What is the total revenue generated by LioCinema and Jotstar during Jan–Nov 2024,
-- considering subscription plans, active duration, and upgrades/downgrades?

with platforms_revenue as (
    select 
        'liocinema' as platform,
        sum(
            (extract(month from age(coalesce(plan_change_date, '2024-11-30'), subscription_date))) *
            case 
                when subscription_plan = 'Basic' then 69
                when subscription_plan = 'Premium' then 129
                else 0
            end
            +
            case when plan_change_date is not null then
                (extract(month from age('2024-11-30', plan_change_date))) *
                case 
                    when new_subscription_plan = 'Basic' then 69
                    when new_subscription_plan = 'Premium' then 129
                    else 0
                end
            else 0 end
        ) as total_revenue
    from liocinema_db.subscribers
    where subscription_date <= '2024-11-30'

    union all

    select 
        'jotstar' as platform,
        sum(
            (extract(month from age(coalesce(plan_change_date, '2024-11-30'), subscription_date))) *
            case 
                when subscription_plan = 'VIP' then 159
                when subscription_plan = 'Premium' then 359
                else 0
            end
            +
            case when plan_change_date is not null then
                (extract(month from age('2024-11-30', plan_change_date))) *
                case 
                    when new_subscription_plan = 'VIP' then 159
                    when new_subscription_plan = 'Premium' then 359
                    else 0
                end
            else 0 end
        ) as total_revenue
    from jotstar_db.subscribers
    where subscription_date <= '2024-11-30'
)
select 
    platform, 
    total_revenue,
    round(total_revenue * 100.0 / sum(total_revenue) over(), 2) as revenue_market_share_pct
from platforms_revenue

